development:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  pool: 5
  database: kaylagram_development
  username: kaylagram
  password:
    
test:
  adapter: postgresql
  encoding: unicode
  database: kaylagram_test
  pool: 5
  username: kaylagram
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kaylagram
  pool: 5
  username: kaylagram
  password: