# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6afc43aa45e3b1078ff907a3fc093b2dfd23be9ea4e4ac0bc19ae34c311f42025d29e8a7c5dee2d1ecd8566bd39c3a3a270d1c3f3ab544da3dcbc6381add1cb3

test:
  secret_key_base: a016f0cc09fe9ee945c9490832033fef2f8ee952e65fc956c8c6edbca3d4ef129237fceac1770b0760a43fbee92ea2bab87ac041ff4e2f97e95caf64b3600c99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
